apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment 
  labels: 
    tier: frontend
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata: #Pod Metadata. Must be children of template section
      name: nginx
      labels:
        app: myapp
    spec: #Pod Spec Section
      containers:
        - name: nginx-container
          image: nginx